### ISSUE TITLE
Implement filtering on fromFile

### ISSUE THREAD

**Issue by delanym** [Ekryd/echo-maven-plugin#144]
I see properties can be used in the message but not in the text file.
It would be handy to say in the text file:

`The default goal is "${project.build.defaultGoal}"`

and read

`The default goal is "clean install"`

**Comment by delanym** [comment]
Maybe there's a clue in https://github.com/mojohaus/properties-maven-plugin

**Comment by Ekryd** [comment]
Hmmm, there was a [ExpansionBuffer.java](https://github.com/mojohaus/properties-maven-plugin/blob/master/src/main/java/org/codehaus/mojo/properties/ExpansionBuffer.java), that may be promising.

It will take some time to look into this though. Otherwise, care to do a PR?

**Comment by delanym** [comment]
I wont promise anything

**Comment by Ekryd** [comment]
Did a few experiments on this and it didn't work out well.
The maven parameters (such as ${project.build.defaultGoal}) does not exist as values anywhere, but they are actually resolved on the fly. I have no idea how they are resolved outside the pom-file. 
I will close this issue for now, since I don't have a way forward on this. Sorry!
